version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Change this to "postgres"
      POSTGRES_DB: dvdrental
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg-network
    network_mode: bridge  # Specify bridge network mode

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - pg-network
    network_mode: bridge  # Specify bridge network mode

networks:
  pg-network:

volumes:
  postgres_data:


